import type { ScalingFrame } from "./scalingTypes";

export const scalingFrames: ScalingFrame[] = [
  // ── Frame 1: Local Application ──
  {
    id: "local-app",
    title: "Local Application",
    description:
      "Before there's any network at all, your app is just a program running on a single computer. The only people who can use it are those who can physically sit at the machine (or maybe a handful of users on the same local network). This is where every project starts — a script, a desktop app, or a local dev server on localhost. It works, but it doesn't scale beyond the people in the room.",
    nodes: [
      {
        id: "user",
        label: "You",
        icon: "\uD83E\uDDD1",
        color: "#6c8cff",
        x: 50,
        y: 20,
      },
      {
        id: "laptop",
        label: "Your Computer",
        icon: "\uD83D\uDCBB",
        color: "#4ade80",
        x: 50,
        y: 60,
        detail: "App + Data Storage",
      },
    ],
    edges: [{ from: "user", to: "laptop", label: "localhost" }],
  },

  // ── Frame 2: Web Server (no DNS) ──
  {
    id: "single-server",
    title: "Single Server",
    description:
      "The first step toward real scale: move your app onto a server with a public IP address so anyone on the internet can reach it. Everything still runs on one box — the web application, the database, the cache — but now users anywhere in the world can connect. The catch? They need to know and type the server's IP address (e.g. 123.456.789.12) to reach you. Not exactly user-friendly, but it works.",
    changeSummary:
      "Move the app to a web server with a public IP, accessible to anyone on the internet.",
    nodes: [
      {
        id: "user",
        label: "User",
        icon: "\uD83D\uDCBB",
        color: "#6c8cff",
        x: 50,
        y: 8,
      },
      {
        id: "server",
        label: "Web Server",
        icon: "\uD83D\uDDA5\uFE0F",
        color: "#4ade80",
        x: 50,
        y: 55,
        detail: "App + Data Storage",
      },
    ],
    edges: [{ from: "user", to: "server", label: "http://123.456.789.12" }],
    newNodeIds: ["server"],
  },

  // ── Frame 3: DNS ──
  {
    id: "dns",
    title: "DNS",
    description:
      "Typing an IP address and port to visit a website is forgettable and error-prone. DNS (Domain Name System) solves this by mapping a human-readable name like www.mysite.com to the server's IP address. Now you can share a memorable URL instead of a string of numbers. DNS is like the phone book of the internet — and it's the first step toward making your service discoverable. This doesn't change how many users your server can handle, but it makes your app accessible to anyone who can remember a name.",
    changeSummary:
      "Add DNS so users can reach the server via a memorable URL instead of an IP address.",
    nodes: [
      {
        id: "user",
        label: "User",
        icon: "\uD83D\uDCBB",
        color: "#6c8cff",
        x: 35,
        y: 8,
      },
      {
        id: "dns",
        label: "DNS",
        icon: "\uD83C\uDF10",
        color: "#a78bfa",
        x: 75,
        y: 8,
      },
      {
        id: "server",
        label: "Web Server",
        icon: "\uD83D\uDDA5\uFE0F",
        color: "#4ade80",
        x: 35,
        y: 55,
        detail: "App + Data Storage",
      },
    ],
    edges: [
      { from: "user", to: "dns", label: "www.mysite.com", offsetY: -3 },
      {
        from: "dns",
        to: "user",
        label: "123.456.789.12",
        style: "solid",
        offsetY: 3,
      },
      { from: "user", to: "server", label: "HTTP requests" },
    ],
    newNodeIds: ["dns"],
  },

  // ── Frame 4: Add a Database ──
  {
    id: "database",
    title: "Separate Database",
    description:
      "With a growing user base, a single all-in-one server isn't enough. We separate the web server (which handles HTTP requests and runs application logic) from the database server (which stores and retrieves data). This separation lets us scale each tier independently — we can upgrade the database hardware without touching the web server, or vice versa.",
    changeSummary: "Split the single server into a web tier and a data tier.",
    nodes: [
      {
        id: "user",
        label: "Users",
        icon: "\uD83D\uDCBB\uD83D\uDCF1",
        color: "#6c8cff",
        x: 35,
        y: 8,
      },
      {
        id: "dns",
        label: "DNS",
        icon: "\uD83C\uDF10",
        color: "#a78bfa",
        x: 75,
        y: 8,
      },
      {
        id: "server",
        label: "Web Server",
        icon: "\uD83D\uDDA5\uFE0F",
        color: "#4ade80",
        x: 35,
        y: 45,
        group: "web-tier",
      },
      {
        id: "db",
        label: "Database",
        icon: "\uD83D\uDDC4\uFE0F",
        color: "#fb923c",
        x: 35,
        y: 82,
        group: "data-tier",
      },
    ],
    groups: [
      {
        id: "web-tier",
        label: "Web Tier",
        x: 15,
        y: 33,
        width: 40,
        height: 22,
      },
      {
        id: "data-tier",
        label: "Data Tier",
        x: 15,
        y: 70,
        width: 40,
        height: 24,
      },
    ],
    edges: [
      { from: "user", to: "dns" },
      { from: "user", to: "server" },
      { from: "server", to: "db", label: "read/write" },
    ],
    newNodeIds: ["db"],
  },

  // ── Frame 5: Load Balancer ──
  {
    id: "load-balancer",
    title: "Load Balancer",
    description:
      "A single web server is a single point of failure (SPOF) — if it goes down, the whole site goes down. A load balancer sits in front of multiple web servers and distributes incoming traffic evenly among them. Users connect to the load balancer's public IP; the web servers sit behind it on private IPs, unreachable directly from the internet. If one server fails, the load balancer routes traffic to the healthy ones.",
    changeSummary:
      "Add a load balancer with multiple web servers for redundancy and capacity.",
    nodes: [
      {
        id: "user",
        label: "Users",
        icon: "\uD83D\uDCBB\uD83D\uDCF1",
        color: "#6c8cff",
        x: 35,
        y: 5,
      },
      {
        id: "dns",
        label: "DNS",
        icon: "\uD83C\uDF10",
        color: "#a78bfa",
        x: 75,
        y: 5,
      },
      {
        id: "lb",
        label: "Load Balancer",
        icon: "\u2696\uFE0F",
        color: "#f472b6",
        x: 35,
        y: 25,
      },
      {
        id: "srv1",
        label: "Server 1",
        icon: "\uD83D\uDDA5\uFE0F",
        color: "#4ade80",
        x: 25,
        y: 48,
        group: "web-tier",
      },
      {
        id: "srv2",
        label: "Server 2",
        icon: "\uD83D\uDDA5\uFE0F",
        color: "#4ade80",
        x: 45,
        y: 48,
        group: "web-tier",
      },
      {
        id: "db",
        label: "Database",
        icon: "\uD83D\uDDC4\uFE0F",
        color: "#fb923c",
        x: 35,
        y: 82,
        group: "data-tier",
      },
    ],
    groups: [
      {
        id: "web-tier",
        label: "Web Tier",
        x: 10,
        y: 37,
        width: 50,
        height: 22,
      },
      {
        id: "data-tier",
        label: "Data Tier",
        x: 15,
        y: 70,
        width: 40,
        height: 24,
      },
    ],
    edges: [
      { from: "user", to: "dns" },
      { from: "user", to: "lb" },
      { from: "lb", to: "srv1" },
      { from: "lb", to: "srv2" },
      { from: "srv1", to: "db" },
      { from: "srv2", to: "db" },
    ],
    newNodeIds: ["lb", "srv1", "srv2"],
  },

  // ── Frame 6: Read Replicas ──
  {
    id: "read-replicas",
    title: "Read Replicas",
    description:
      "Most applications are read-heavy — far more reads than writes. To scale the data tier, we add read replicas (followers) that replicate data from the leader (primary) database. All write operations go to the leader, which then replicates changes to the followers. Read operations are distributed across the followers. If the leader goes down, a follower can be promoted to become the new leader.",
    changeSummary:
      "Add follower databases for read scaling; leader handles all writes.",
    nodes: [
      {
        id: "user",
        label: "Users",
        icon: "\uD83D\uDCBB\uD83D\uDCF1",
        color: "#6c8cff",
        x: 35,
        y: 5,
      },
      {
        id: "dns",
        label: "DNS",
        icon: "\uD83C\uDF10",
        color: "#a78bfa",
        x: 75,
        y: 5,
      },
      {
        id: "lb",
        label: "Load Balancer",
        icon: "\u2696\uFE0F",
        color: "#f472b6",
        x: 35,
        y: 22,
      },
      {
        id: "srv1",
        label: "Server 1",
        icon: "\uD83D\uDDA5\uFE0F",
        color: "#4ade80",
        x: 25,
        y: 42,
        group: "web-tier",
      },
      {
        id: "srv2",
        label: "Server 2",
        icon: "\uD83D\uDDA5\uFE0F",
        color: "#4ade80",
        x: 45,
        y: 42,
        group: "web-tier",
      },
      {
        id: "leader",
        label: "Leader DB",
        icon: "\uD83D\uDDC4\uFE0F",
        color: "#fb923c",
        x: 20,
        y: 75,
        group: "data-tier",
      },
      {
        id: "followers",
        label: "Followers",
        icon: "\uD83D\uDDC4\uFE0F\uD83D\uDDC4\uFE0F\uD83D\uDDC4\uFE0F",
        color: "#fbbf24",
        x: 55,
        y: 75,
        group: "data-tier",
      },
    ],
    groups: [
      {
        id: "web-tier",
        label: "Web Tier",
        x: 10,
        y: 33,
        width: 50,
        height: 18,
      },
      {
        id: "data-tier",
        label: "Data Tier",
        x: 5,
        y: 63,
        width: 65,
        height: 25,
      },
    ],
    edges: [
      { from: "user", to: "dns" },
      { from: "user", to: "lb" },
      { from: "lb", to: "srv1" },
      { from: "lb", to: "srv2" },
      { from: "srv1", to: "leader", label: "writes" },
      { from: "srv2", to: "leader", label: "writes" },
      { from: "srv1", to: "followers", label: "reads" },
      { from: "srv2", to: "followers", label: "reads" },
      { from: "leader", to: "followers", label: "replicate", style: "solid" },
    ],
    newNodeIds: ["leader", "followers"],
  },

  // ── Frame 7: Cache Layer ──
  {
    id: "cache",
    title: "Cache Layer",
    description:
      'A cache is a temporary key-value storage layer that holds frequently accessed data in memory (RAM), which is much faster than reading from disk (the database). When a request comes in, the server first checks the cache. If the data is there (a "cache hit"), it returns immediately — no database query needed. If not (a "cache miss"), it reads from the database, stores the result in cache for next time, and returns. This dramatically reduces database load and improves response times. However, you\'ll need to pick a cache invalidation strategy so you don\'t read stale data.',
    changeSummary:
      "Add an in-memory cache (e.g. Redis/Memcached) between the web tier and the data tier.",
    nodes: [
      {
        id: "user",
        label: "Users",
        icon: "\uD83D\uDCBB\uD83D\uDCF1",
        color: "#6c8cff",
        x: 35,
        y: 5,
      },
      {
        id: "dns",
        label: "DNS",
        icon: "\uD83C\uDF10",
        color: "#a78bfa",
        x: 75,
        y: 5,
      },
      {
        id: "lb",
        label: "Load Balancer",
        icon: "\u2696\uFE0F",
        color: "#f472b6",
        x: 35,
        y: 20,
      },
      {
        id: "servers",
        label: "Servers",
        icon: "\uD83D\uDDA5\uFE0F\uD83D\uDDA5\uFE0F\uD83D\uDDA5\uFE0F",
        color: "#4ade80",
        x: 35,
        y: 39,
        group: "web-tier",
      },
      {
        id: "cache",
        label: "Cache",
        icon: "\u26A1",
        color: "#f97316",
        x: 68,
        y: 60,
        group: "data-tier",
      },
      {
        id: "leader",
        label: "Leader DB",
        icon: "\uD83D\uDDC4\uFE0F",
        color: "#fb923c",
        x: 20,
        y: 75,
        group: "data-tier",
      },
      {
        id: "followers",
        label: "Followers",
        icon: "\uD83D\uDDC4\uFE0F\uD83D\uDDC4\uFE0F\uD83D\uDDC4\uFE0F",
        color: "#fbbf24",
        x: 50,
        y: 75,
        group: "data-tier",
      },
    ],
    groups: [
      {
        id: "web-tier",
        label: "Web Tier",
        x: 10,
        y: 30,
        width: 50,
        height: 18,
      },
      {
        id: "data-tier",
        label: "Data Tier",
        x: 5,
        y: 52,
        width: 80,
        height: 38,
      },
    ],
    edges: [
      { from: "user", to: "dns" },
      { from: "user", to: "lb" },
      { from: "lb", to: "servers" },
      { from: "servers", to: "cache" },
      { from: "servers", to: "leader", label: "writes" },
      { from: "servers", to: "followers", label: "reads" },
      { from: "leader", to: "followers", label: "replicate", style: "solid" },
    ],
    newNodeIds: ["cache"],
  },

  // ── Frame 8: CDN ──
  {
    id: "cdn",
    title: "CDN",
    description:
      "A Content Delivery Network (CDN) is a geographically distributed network of servers that cache and serve static content — images, CSS, JavaScript, videos — from locations close to the user. Instead of every request for a logo traveling all the way to your origin server, the CDN serves it from an edge server nearby. This reduces latency for users, offloads bandwidth from your servers, and improves availability. Dynamic API requests still go to your origin servers.",
    changeSummary:
      "Add a CDN for static assets (images, CSS, JS) to reduce latency and server load.",
    nodes: [
      {
        id: "user",
        label: "Users",
        icon: "\uD83D\uDCBB\uD83D\uDCF1",
        color: "#6c8cff",
        x: 35,
        y: 5,
      },
      {
        id: "dns",
        label: "DNS",
        icon: "\uD83C\uDF10",
        color: "#a78bfa",
        x: 75,
        y: 5,
      },
      {
        id: "cdn",
        label: "CDN",
        icon: "\u2601\uFE0F",
        color: "#38bdf8",
        x: 80,
        y: 25,
      },
      {
        id: "lb",
        label: "Load Balancer",
        icon: "\u2696\uFE0F",
        color: "#f472b6",
        x: 35,
        y: 33,
        group: "dc",
      },
      {
        id: "servers",
        label: "Servers",
        icon: "\uD83D\uDDA5\uFE0F\uD83D\uDDA5\uFE0F\uD83D\uDDA5\uFE0F",
        color: "#4ade80",
        x: 35,
        y: 48,
        group: "dc",
      },
      {
        id: "cache",
        label: "Cache",
        icon: "\u26A1",
        color: "#f97316",
        x: 68,
        y: 65,
        group: "dc",
      },
      {
        id: "leader",
        label: "Leader DB",
        icon: "\uD83D\uDDC4\uFE0F",
        color: "#fb923c",
        x: 20,
        y: 80,
        group: "dc",
      },
      {
        id: "followers",
        label: "Followers",
        icon: "\uD83D\uDDC4\uFE0F\uD83D\uDDC4\uFE0F\uD83D\uDDC4\uFE0F",
        color: "#fbbf24",
        x: 50,
        y: 80,
        group: "dc",
      },
    ],
    groups: [
      {
        id: "dc",
        label: "Data Center",
        x: 3,
        y: 26,
        width: 72,
        height: 62,
      },
    ],
    edges: [
      { from: "user", to: "dns" },
      { from: "user", to: "cdn", label: "static content" },
      { from: "user", to: "lb", label: "API" },
      { from: "lb", to: "servers" },
      { from: "servers", to: "cache" },
      { from: "servers", to: "leader", label: "writes" },
      { from: "servers", to: "followers", label: "reads" },
      { from: "leader", to: "followers", label: "replicate", style: "solid" },
    ],
    newNodeIds: ["cdn"],
  },

  // ── Frame 9: Stateless Web Tier ──
  {
    id: "stateless",
    title: "Stateless Web Tier",
    description:
      'If a web server stores session data (like login state) in memory, that user\'s requests must always be routed to the same server — this is called "sticky sessions" or load balancer affinity. Sticky sessions are also required for persistent connections like WebSockets, since the connection must stay pinned to the server that accepted it. This coupling makes scaling painful. The fix: move session data out of the web servers and into a shared store (like a NoSQL database or Redis). Now any server can handle any stateless request, because state lives externally. This makes the web tier much easier to scale — servers become interchangeable, and we can auto-scale them up or down freely. (WebSocket connections still need affinity, but the blast radius is smaller when all other state is externalized.)',
    changeSummary:
      "Move session data to a shared NoSQL store, making web servers stateless and interchangeable.",
    nodes: [
      {
        id: "user",
        label: "Users",
        icon: "\uD83D\uDCBB\uD83D\uDCF1",
        color: "#6c8cff",
        x: 35,
        y: 5,
      },
      {
        id: "dns",
        label: "DNS",
        icon: "\uD83C\uDF10",
        color: "#a78bfa",
        x: 75,
        y: 5,
      },
      {
        id: "cdn",
        label: "CDN",
        icon: "\u2601\uFE0F",
        color: "#38bdf8",
        x: 80,
        y: 18,
      },
      {
        id: "lb",
        label: "Load Balancer",
        icon: "\u2696\uFE0F",
        color: "#f472b6",
        x: 35,
        y: 33,
        group: "dc",
      },
      {
        id: "servers",
        label: "Servers",
        icon: "\uD83D\uDDA5\uFE0F\uD83D\uDDA5\uFE0F\uD83D\uDDA5\uFE0F",
        color: "#4ade80",
        x: 35,
        y: 48,
        group: "dc",
      },
      {
        id: "cache",
        label: "Cache",
        icon: "\u26A1",
        color: "#f97316",
        x: 55,
        y: 80,
        group: "dc",
      },
      {
        id: "nosql",
        label: "NoSQL",
        icon: "\uD83D\uDCC4",
        color: "#c084fc",
        x: 72,
        y: 80,
        group: "dc",
      },
      {
        id: "leader",
        label: "Leader DB",
        icon: "\uD83D\uDDC4\uFE0F",
        color: "#fb923c",
        x: 18,
        y: 80,
        group: "dc",
      },
      {
        id: "followers",
        label: "Followers",
        icon: "\uD83D\uDDC4\uFE0F\uD83D\uDDC4\uFE0F\uD83D\uDDC4\uFE0F",
        color: "#fbbf24",
        x: 40,
        y: 80,
        group: "dc",
      },
    ],
    groups: [
      {
        id: "dc",
        label: "Data Center",
        x: 3,
        y: 26,
        width: 82,
        height: 62,
      },
    ],
    edges: [
      { from: "user", to: "dns" },
      { from: "user", to: "cdn" },
      { from: "user", to: "lb" },
      { from: "lb", to: "servers" },
      { from: "servers", to: "nosql", label: "sessions", style: "solid" },
      { from: "servers", to: "cache" },
      { from: "servers", to: "leader", label: "writes" },
      { from: "servers", to: "followers", label: "reads" },
      { from: "leader", to: "followers", label: "replicate", style: "solid" },
    ],
    newNodeIds: ["nosql"],
  },

  // ── Frame 10: Message Queue + Workers ──
  {
    id: "message-queue",
    title: "Message Queue + Workers",
    description:
      "Some operations are too slow or resource-intensive to handle synchronously in a web request — sending emails, processing images, generating reports, running ML models. A message queue (like RabbitMQ, Kafka, or SQS) decouples producers (web servers) from consumers (workers). The web server publishes a task to the queue and immediately responds to the user. Worker processes pick up tasks from the queue and process them asynchronously. This makes the system more loosely coupled and failure resilient — if a worker crashes, the message stays in the queue and gets picked up by another worker. Beyond the main application, async events also power internal tools, observability dashboards, aggregated statistics, and debug logs — all of which need to talk to the database without blocking user-facing requests.",
    changeSummary:
      "Add a message queue for async processing — web servers publish, workers consume.",
    nodes: [
      {
        id: "user",
        label: "Users",
        icon: "\uD83D\uDCBB\uD83D\uDCF1",
        color: "#6c8cff",
        x: 25,
        y: 15,
      },
      {
        id: "dns",
        label: "DNS",
        icon: "\uD83C\uDF10",
        color: "#a78bfa",
        x: 60,
        y: 10,
      },
      {
        id: "cdn",
        label: "CDN",
        icon: "\u2601\uFE0F",
        color: "#38bdf8",
        x: 80,
        y: 15,
      },
      {
        id: "lb",
        label: "Load Balancer",
        icon: "\u2696\uFE0F",
        color: "#f472b6",
        x: 25,
        y: 29,
        group: "dc",
      },
      {
        id: "servers",
        label: "Servers",
        icon: "\uD83D\uDDA5\uFE0F",
        color: "#4ade80",
        x: 25,
        y: 45,
        group: "dc",
      },
      {
        id: "mq",
        label: "Message\nQueue",
        icon: "\uD83D\uDCE8",
        color: "#fb7185",
        x: 60,
        y: 45,
        group: "dc",
      },
      {
        id: "nosql",
        label: "NoSQL",
        icon: "\uD83D\uDCC4",
        color: "#c084fc",
        x: 35,
        y: 70,
        group: "dc",
      },
      {
        id: "workers",
        label: "Workers",
        icon: "\u2699\uFE0F",
        color: "#a3e635",
        x: 80,
        y: 70,
        group: "dc",
      },
      {
        id: "db",
        label: "Databases",
        icon: "\uD83D\uDDC4\uFE0F",
        color: "#fb923c",
        x: 60,
        y: 70,
        group: "dc",
      },
      {
        id: "cache",
        label: "Cache",
        icon: "\u26A1",
        color: "#f97316",
        x: 13,
        y: 70,
        group: "dc",
      },
      {
        id: "internal-tools",
        label: "Internal\nTools",
        icon: "\uD83D\uDEE0\uFE0F",
        color: "#7dd3fc",
        x: 15,
        y: 92,
      },
      {
        id: "monitoring",
        label: "Observability\nDashboards",
        icon: "\uD83D\uDCCA",
        color: "#86efac",
        x: 38,
        y: 92,
      },
      {
        id: "agg-stats",
        label: "Aggregated\nStatistics",
        icon: "\uD83D\uDCC8",
        color: "#fde68a",
        x: 61,
        y: 92,
      },
      {
        id: "debug-logs",
        label: "Debug\nLogs",
        icon: "\uD83D\uDC1B",
        color: "#fca5a5",
        x: 84,
        y: 92,
      },
    ],
    groups: [
      { id: "dc", label: "Data Center", x: 2, y: 22, width: 90, height: 58 },
    ],
    edges: [
      { from: "user", to: "dns" },
      { from: "user", to: "cdn" },
      { from: "user", to: "lb" },
      { from: "lb", to: "servers" },
      { from: "servers", to: "mq", label: "publish" },
      { from: "mq", to: "workers", label: "consume" },
      { from: "servers", to: "nosql" },
      { from: "servers", to: "db" },
      { from: "servers", to: "cache" },
      { from: "workers", to: "db" },
      { from: "internal-tools", to: "db" },
      { from: "monitoring", to: "db" },
      { from: "agg-stats", to: "db" },
      { from: "debug-logs", to: "db" },
    ],
    newNodeIds: [
      "mq",
      "workers",
      "internal-tools",
      "monitoring",
      "agg-stats",
      "debug-logs",
    ],
  },

  // ── Frame 11: Database Sharding ──
  {
    id: "sharding",
    title: "Database Sharding",
    description:
      'As the data grows beyond what a single database server can handle, we shard — splitting the data across multiple database servers, each holding a subset ("shard") of the total data. For example, we might shard by user ID using modulo arithmetic: user_id % N determines which shard a user\'s data lives on (0 → Shard 1, 1 → Shard 2, ..., N-1 → Shard N). Each shard is an independent database. Sharding enables near-linear horizontal scaling of the data tier, but adds complexity — cross-shard queries are harder, and the sharding key choice is critical.',
    changeSummary:
      "Shard the database tier — partition data across multiple independent database servers.",
    nodes: [
      {
        id: "user",
        label: "Users",
        icon: "\uD83D\uDCBB\uD83D\uDCF1",
        color: "#6c8cff",
        x: 25,
        y: 15,
      },
      {
        id: "dns",
        label: "DNS",
        icon: "\uD83C\uDF10",
        color: "#a78bfa",
        x: 60,
        y: 10,
      },
      {
        id: "cdn",
        label: "CDN",
        icon: "\u2601\uFE0F",
        color: "#38bdf8",
        x: 80,
        y: 15,
      },
      {
        id: "lb",
        label: "Load Balancer",
        icon: "\u2696\uFE0F",
        color: "#f472b6",
        x: 25,
        y: 29,
        group: "dc",
      },
      {
        id: "servers",
        label: "Web Servers",
        icon: "\uD83D\uDDA5\uFE0F",
        color: "#4ade80",
        x: 25,
        y: 43,
        group: "dc",
      },
      {
        id: "mq",
        label: "Message\nQueue",
        icon: "\uD83D\uDCE8",
        color: "#fb7185",
        x: 60,
        y: 43,
        group: "dc",
      },
      {
        id: "workers",
        label: "Workers",
        icon: "\u2699\uFE0F",
        color: "#a3e635",
        x: 80,
        y: 59,
        group: "dc",
      },
      {
        id: "shard1",
        label: "Shard 1",
        icon: "\uD83D\uDDC4\uFE0F",
        color: "#fb923c",
        x: 40,
        y: 82,
        group: "db-shards",
      },
      {
        id: "shard2",
        label: "Shard 2",
        icon: "\uD83D\uDDC4\uFE0F",
        color: "#fb923c",
        x: 50,
        y: 82,
        group: "db-shards",
      },
      {
        id: "ellipsis",
        label: "\u2026",
        icon: "",
        color: "#94a3b8",
        x: 60,
        y: 82,
        group: "db-shards",
      },
      {
        id: "shard3",
        label: "Shard N",
        icon: "\uD83D\uDDC4\uFE0F",
        color: "#fb923c",
        x: 72,
        y: 82,
        group: "db-shards",
      },
      {
        id: "cache",
        label: "Cache",
        icon: "\u26A1",
        color: "#f97316",
        x: 13,
        y: 70,
        group: "dc",
      },
      {
        id: "nosql",
        label: "NoSQL",
        icon: "\uD83D\uDCC4",
        color: "#c084fc",
        x: 25,
        y: 70,
        group: "dc",
      },
    ],
    groups: [
      { id: "dc", label: "Data Center", x: 2, y: 22, width: 90, height: 72 },
      {
        id: "db-shards",
        label: "Sharded Databases",
        x: 30,
        y: 74,
        width: 48,
        height: 17,
      },
    ],
    edges: [
      { from: "user", to: "dns" },
      { from: "user", to: "cdn" },
      { from: "user", to: "lb" },
      { from: "lb", to: "servers" },
      { from: "servers", to: "mq", label: "publish" },
      { from: "mq", to: "workers", label: "consume" },
      { from: "servers", to: "nosql" },
      { from: "servers", to: "shard1" },
      { from: "servers", to: "shard2" },
      { from: "servers", to: "shard3" },
      { from: "servers", to: "cache" },
      { from: "workers", to: "shard1" },
      { from: "workers", to: "shard2" },
      { from: "workers", to: "shard3" },
    ],
    newNodeIds: ["shard1", "shard2", "shard3"],
  },

  // ── Frame 12: Multiple Data Centers ──
  {
    id: "data-centers",
    title: "Multiple Data Centers",
    description:
      "To serve users globally with low latency, we deploy the application across multiple data centers in different geographic regions. GeoDNS routes users to the nearest data center based on their location — a user in New York hits the US-East DC, while a user in Tokyo hits the Asia DC. Each data center has its own load balancer, web servers, database replicas, and caches. If one data center goes down, DNS routes all traffic to the remaining healthy ones.",
    changeSummary:
      "Deploy across multiple data centers with GeoDNS routing traffic to the nearest region.",
    nodes: [
      {
        id: "user",
        label: "Users",
        icon: "\uD83D\uDCBB\uD83D\uDCF1",
        color: "#6c8cff",
        x: 25,
        y: 13,
      },
      {
        id: "dns",
        label: "GeoDNS",
        icon: "\uD83C\uDF10",
        color: "#a78bfa",
        x: 60,
        y: 8,
      },
      {
        id: "cdn",
        label: "CDN",
        icon: "\u2601\uFE0F",
        color: "#38bdf8",
        x: 80,
        y: 20,
      },
      {
        id: "lb1",
        label: "LB",
        icon: "\u2696\uFE0F",
        color: "#f472b6",
        x: 13,
        y: 32,
        group: "dc1",
      },
      {
        id: "dc1-srv",
        label: "Servers",
        icon: "\uD83D\uDDA5\uFE0F",
        color: "#4ade80",
        x: 13,
        y: 46,
        group: "dc1",
      },
      {
        id: "dc1-mq",
        label: "MQ",
        icon: "\uD83D\uDCE8",
        color: "#fb7185",
        x: 35,
        y: 46,
        group: "dc1",
      },
      {
        id: "dc1-workers",
        label: "Workers",
        icon: "\u2699\uFE0F",
        color: "#a3e635",
        x: 35,
        y: 58,
        group: "dc1",
      },
      {
        id: "dc1-cache",
        label: "Cache",
        icon: "\u26A1",
        color: "#f97316",
        x: 8,
        y: 75,
        group: "dc1",
      },
      {
        id: "dc1-nosql",
        label: "NoSQL",
        icon: "\uD83D\uDCC4",
        color: "#c084fc",
        x: 22,
        y: 75,
        group: "dc1",
      },
      {
        id: "dc1-db",
        label: "Databases",
        icon: "\uD83D\uDDC4\uFE0F",
        color: "#fb923c",
        x: 35,
        y: 75,
        group: "dc1",
      },
      {
        id: "lb2",
        label: "LB",
        icon: "\u2696\uFE0F",
        color: "#f472b6",
        x: 58,
        y: 32,
        group: "dc2",
      },
      {
        id: "dc2-srv",
        label: "Servers",
        icon: "\uD83D\uDDA5\uFE0F",
        color: "#4ade80",
        x: 58,
        y: 46,
        group: "dc2",
      },
      {
        id: "dc2-mq",
        label: "MQ",
        icon: "\uD83D\uDCE8",
        color: "#fb7185",
        x: 82,
        y: 46,
        group: "dc2",
      },
      {
        id: "dc2-workers",
        label: "Workers",
        icon: "\u2699\uFE0F",
        color: "#a3e635",
        x: 82,
        y: 58,
        group: "dc2",
      },
      {
        id: "dc2-cache",
        label: "Cache",
        icon: "\u26A1",
        color: "#f97316",
        x: 55,
        y: 75,
        group: "dc2",
      },
      {
        id: "dc2-nosql",
        label: "NoSQL",
        icon: "\uD83D\uDCC4",
        color: "#c084fc",
        x: 68,
        y: 75,
        group: "dc2",
      },
      {
        id: "dc2-db",
        label: "Databases",
        icon: "\uD83D\uDDC4\uFE0F",
        color: "#fb923c",
        x: 82,
        y: 75,
        group: "dc2",
      },
    ],
    groups: [
      { id: "dc1", label: "DC1 — US-East", x: 2, y: 24, width: 46, height: 62 },
      {
        id: "dc2",
        label: "DC2 — US-West",
        x: 49,
        y: 24,
        width: 46,
        height: 62,
      },
    ],
    edges: [
      { from: "user", to: "dns" },
      { from: "user", to: "cdn" },
      { from: "user", to: "lb1", label: "geo-routed" },
      { from: "user", to: "lb2" },
      { from: "lb1", to: "dc1-srv" },
      { from: "dc1-srv", to: "dc1-mq" },
      { from: "dc1-mq", to: "dc1-workers" },
      { from: "dc1-srv", to: "dc1-db" },
      { from: "dc1-srv", to: "dc1-cache" },
      { from: "dc1-srv", to: "dc1-nosql" },
      { from: "dc1-workers", to: "dc1-db" },
      { from: "lb2", to: "dc2-srv" },
      { from: "dc2-srv", to: "dc2-mq" },
      { from: "dc2-mq", to: "dc2-workers" },
      { from: "dc2-srv", to: "dc2-db" },
      { from: "dc2-srv", to: "dc2-cache" },
      { from: "dc2-srv", to: "dc2-nosql" },
      { from: "dc2-workers", to: "dc2-db" },
    ],
    newNodeIds: [
      "lb1",
      "dc1-srv",
      "dc1-mq",
      "dc1-workers",
      "dc1-db",
      "dc1-cache",
      "dc1-nosql",
      "lb2",
      "dc2-srv",
      "dc2-mq",
      "dc2-workers",
      "dc2-db",
      "dc2-cache",
      "dc2-nosql",
    ],
  },
];
